spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.200.134:5432/stdatabasehml?currentSchema=public}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:915G@vmn245@@}
